# Generated by Django 3.2.6 on 2021-08-25 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("api", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="members_pins",
            field=models.ManyToManyField(through="api.PinnedTicket", to="api.Member"),
        )
    ]
