# Generated by Django 3.0.8 on 2020-07-08 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_snippit'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Snippit',
            new_name='Snippet',
        ),
    ]
