# Generated by Django 4.0.6 on 2023-03-11 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_event_id_alter_tag_id_alter_team_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
