# Generated by Django 3.0.8 on 2020-07-10 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20200710_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='completed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='started',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
