# Generated by Django 3.0.8 on 2020-07-10 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20200710_0014'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Snippet',
        ),
    ]
